import { Knex } from 'knex'

export async function up (knex: Knex): Promise<void> {
  return await knex.schema.createTable('stores', table => {
    table.string('id').primary().unique()
    table.string('name')
    table.string('officialName')
    table.string('socialName')
    table.string('type', 50)
    table.text('description')
    table.string('email')
    table.string('phoneNumber')
    table.string('website')
    table.string('floor')
    table.string('shoppingCode')
    table.string('openDate', 10)
    table.string('closeDate', 10)
    table.string('luc')
    table.string('externalId')
    table.string('shoppingId')
    table.string('segment1')
    table.string('segment2')
    table.string('segment3')
    table.string('roomNumber')
    table.string('tower')
    table.string('menuURL')
    table.string('reservationURL')
    table.string('ifoodURL')
    table.string('deliveyCenterURL')
    table.string('cupomURL')
    table.string('rappiURL')
    table.text('keywords')
    table.string('driveThru')
    table.string('lockers')
    table.string('whatsapp')
    table.string('field1')
    table.string('field2')
    table.string('field3')
    table.string('field4')
    table.string('field5')
    table.string('field6')
    table.string('field7')
    table.string('field8')
    table.string('field9')
    table.string('cnpj')
    table.string('lastModifiedDate')
    table.string('imageURL')
    table.dateTime('created_at').defaultTo(knex.fn.now()).notNullable()
  })
}

export async function down (knex: Knex): Promise<void> {
  return await knex.schema.dropTable('stores')
}
